/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BookTransactionHistoryResponse } from '../models/book-transaction-history-response';
export interface PageResponseBookTransactionHistoryResponse {
  content?: Array<BookTransactionHistoryResponse>;
  first?: boolean;
  last?: boolean;
  number?: number;
  size?: number;
  totalElements?: number;
  totalPages?: number;
}
